packages:
  - .
  - examples/*

overrides:
  'vitepress>vite': 8.2.1
  vite: 'catalog:'
  vitest: 'catalog:'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vitest: 5.0.0
  vite-plus: 0.2.8
  '@vitest/coverage-v8': 5.0.0
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
allowBuilds:
  esbuild: true
  workerd: true
